---
# List of custom programs to install that are not packaged. These each require
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.
bio_general:
 #- bio4j # no easy download for 0.8
 - anaconda
 - emboss
 - pgdspider
bio_nextgen:
  alignment:
    - bwa
    - bowtie
    - gmap
    - lastz
    - mosaik
    # - perm # difficult build process with directory names
    - snap
    - star
    #- stampy # no version names on tarballs
  utilities:
    - bamtools
    - biobambam
    - cram
    - dwgsim
    - fastq_screen
    - fastx_toolkit
    - ogap
    - rnaseqc
    - varianttools
  analysis:
    - cufflinks
    # - echo # build problems on ubuntu 12.10
    - picard
    - sambamba
    - shrec
    - tophat
    # - vep # lots of timeout failures on download
  assembly:
    - abyss
    - cortex_var
    - ray
    - transabyss
    - trinity
    - velvet
  sv:
    - hydra
    - freec
  variant:
    - bcbio_variation
    - crisp
    - freebayes
    - gatk
    #- gatk_protected
    - gemini
    - grabix
    - mutect
    - pbgzip
    - tassel
    - snpeff
    - stacks
    - varscan
    - vcflib
  chip:
    - macs
  needs_64bit:
    - ucsc_tools
    - bfast
    - plink_seq
bio_proteomics:
  - transproteomic_pipeline
  - omssa
  - mzmine
  - myrimatch
  - directag
  - tagrecon
  - idpqonvert
  - pepitome
  - percolator
bio_proteomics_wine:
  - proteomics_wine_env
  #- multiplierz
  - proteowizard
  - morpheus
cloudman:
  - nginx
  - proftpd
  - sge
  - novnc
galaxy:
  - galaxy_webapp
galaxy_tools:
  - cbl_galaxy_tools
galaxyp:
  - galaxy_protk
  - protvis
distributed:
  - gnu_parallel
  - pydoop
  - seal
system:
  - homebrew
  - s3fs
python:
  - bx-python
  - netsa-python
  - rpy
java:
  - leiningen
phylogeny:
  - tracer
  - beast
#Viral Cloud Resource (VCR) - JCVI's Viral Genomic Pipelines on the cloud
vcr:
  - viralassembly
  - viralassembly_cleanall
  - viralvigor
  - viralvigor_test
  - viralvigor_validate
  - viralvigor_cleanall
bio_kepler:
  kepler:
    - biokepler
  rRNA_prediction:
    - hmm_rrna
    - blast_rrna
  tRNA_prediction:
    - trnascan-se
  function_annotation:
    - cog
    - kog
    - prk
    - pfam
    - tigrfam
  pathway_annotation:
    - kegg
  variant_calling:
    - breakdancer
  integrated_bioinformatics_environment:
    - mothur
    - qiime
  orf_prediction:
    - orf_finder
    - metagene
    - fraggene_scan
  sequence_information:
    - fna_stat
    - faa_stat
  quality_control:
    - qc_filter_fastq
    - qc_filter
    - trim
#    - uchime already installed on cloudbiolinux
  format_conversion:
    - fastq2fasta
  alignment:
#    - blastall already installed on cloudbiolinux
#    - bowtie already installed on cloudbiolinux
#    - bwa already installed on cloudbiolinux
    - soap
#    - samtools already installed on cloudbiolinux
  assembly:
    - soapdenovo
    - ssake
#    - velvet already installed on cloudbiolinux
  GUI_for_bioinformatics:
#    - cytoscape already installed on cloudbiolinux
#    - rasmol already installed on cloudbiolinux
  multiple_sequence_alignment:
#    - clustalw already installed on cloudbiolinux
#    - clustalx already installed on cloudbiolinux
#    - muscle already installed on cloudbiolinux
  RNA-seq_analysis:
#    - tophat already installed on cloudbiolinux
#    - cuffdiff already installed on cloudbiolinux
  clustering:
    - cd-hit
    - cd-hit-454
    - cd-hit-est
# ToDo -- test on 64bit with bfast
#- dnaa
#- srma
